# Site settings
title: Resolve Digital
description: >
  We build, optimize and maintain stores for innovative eCommerce retailers.
  Specializing in Solidus, Spree, Ruby on Rails, iOS and Machine Learning
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://resolve.digital"

cdn: "https://resolve.imgix.net"
cdn_params: "?auto=format&ch=Width,DPR"

highlighter: pygments

# Build settings
markdown: kramdown

sass:
  style: compressed

people: &default
  - david_jones
  - mark_haylock
  - barry_harrison
  - tim_ross
  - isaac_freeman

authors: *default
editors: *default

permalink: "/blog/posts/:title/"
